# Generated by Django 2.2.4 on 2019-08-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0005_auto_20190822_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateTimeField(verbose_name='Date of Birth'),
        ),
    ]
